// Time Machine — scenario deck.
// Prices are indexed (not dollar values); keyframes are [t 0..1, level] and get
// interpolated with seeded noise so the chart shape matches the real move.
// outcomePct = approximate real move over the month after the cutoff.
const SCENARIOS = [
  {
    id: 'nvda-2022',
    ticker: 'NVDA',
    name: 'Nvidia',
    revealDate: 'October 2022',
    story: 'The chip nobody wants',
    headlines: [
      'Washington bans exports of high-end AI chips to China.',
      'Gaming GPU inventory piles up as crypto mining demand evaporates.',
      'The stock has lost roughly two-thirds of its value in under a year.',
    ],
    pre: [[0, 100], [0.12, 92], [0.25, 68], [0.38, 55], [0.5, 62], [0.62, 44], [0.75, 40], [0.88, 33], [1, 31]],
    post: [[0, 31], [0.3, 34], [0.6, 38], [0.8, 40], [1, 41]],
    outcomePct: +32,
    blurb: 'This was Nvidia at the October 2022 bottom — down ~65% from its peak. Within a month it rallied over 30%, and ChatGPT launched weeks later. Buying the most hated chip stock on earth turned out to be the trade of the decade.',
  },
  {
    id: 'enron-2001',
    ticker: 'ENE',
    name: 'Enron',
    revealDate: 'October 2001',
    story: 'A few questions for the CFO',
    headlines: [
      'The SEC opens an "informal inquiry" into related-party transactions.',
      'The company takes a surprise $1.2 billion writedown against equity.',
      'Management insists the core business has never been stronger.',
    ],
    pre: [[0, 100], [0.15, 92], [0.3, 70], [0.45, 58], [0.6, 52], [0.75, 44], [0.9, 40], [1, 37]],
    post: [[0, 37], [0.25, 22], [0.5, 12], [0.75, 8], [1, 4]],
    outcomePct: -88,
    blurb: 'This was Enron, October 2001. "Informal inquiry" became fraud investigation, the writedown became a restatement, and within weeks the seventh-largest US company was headed to bankruptcy. When management says the core business has never been stronger — check the footnotes.',
  },
  {
    id: 'btc-2017',
    ticker: 'BTC',
    name: 'Bitcoin',
    revealDate: 'December 2017',
    story: 'Your uncle just asked how to buy it',
    headlines: [
      'CME launches futures trading on the asset this week.',
      'Coinbase hits #1 on the App Store as sign-ups overwhelm servers.',
      'Up roughly 20x in twelve months; talk shows can\'t stop covering it.',
    ],
    pre: [[0, 8], [0.2, 12], [0.4, 18], [0.55, 26], [0.7, 40], [0.82, 58], [0.92, 82], [1, 100]],
    post: [[0, 100], [0.2, 78], [0.45, 68], [0.7, 72], [1, 60]],
    outcomePct: -40,
    blurb: 'Bitcoin, December 2017 — within days of the exact top near $20,000. The futures launch marked the peak almost to the hour, and it fell ~40% in a month and ~83% over the next year. When your uncle asks how to buy it, the marginal buyer may already be in.',
  },
  {
    id: 'aapl-2018',
    ticker: 'AAPL',
    name: 'Apple',
    revealDate: 'December 2018',
    story: 'They stopped telling us the number',
    headlines: [
      'The company will no longer report iPhone unit sales.',
      'Asian suppliers guide down on weaker-than-expected orders.',
      'Tariff headlines out of Washington rattle hardware names.',
    ],
    pre: [[0, 72], [0.2, 82], [0.4, 92], [0.55, 100], [0.7, 88], [0.85, 80], [1, 76]],
    post: [[0, 76], [0.3, 72], [0.6, 68], [0.8, 61], [1, 62]],
    outcomePct: -18,
    blurb: 'Apple, December 2018. A month later came the first revenue warning since 2002 — China iPhone sales had cracked, exactly what hiding the unit numbers foreshadowed. (The next year it doubled. Timing is everything.)',
  },
  {
    id: 'gme-2021',
    ticker: 'GME',
    name: 'GameStop',
    revealDate: 'January 2021',
    story: 'The shorts are trapped',
    headlines: [
      'Short interest exceeds 100% of the float.',
      'A Reddit forum is coordinating the most crowded trade on earth.',
      'The stock is up ~1,700% this month; hedge funds are bleeding.',
    ],
    pre: [[0, 3], [0.25, 4], [0.5, 6], [0.65, 10], [0.78, 22], [0.88, 45], [0.95, 72], [1, 100]],
    post: [[0, 100], [0.15, 46], [0.35, 18], [0.6, 12], [0.8, 10], [1, 14]],
    outcomePct: -85,
    blurb: 'GameStop at the January 27, 2021 peak. The next morning brokers restricted buying and it fell ~85% in a month. The squeeze was real — so was the round trip. Vertical charts resolve vertically, in both directions.',
  },
  {
    id: 'meta-2022',
    ticker: 'META',
    name: 'Meta',
    revealDate: 'November 2022',
    story: 'Ten billion a year on legs that don\'t exist',
    headlines: [
      'Metaverse division is burning $10B+ a year with no product in sight.',
      'First revenue decline in company history; the stock trades at 2016 levels.',
      'Reports of the first mass layoffs ever are circulating.',
    ],
    pre: [[0, 100], [0.15, 88], [0.3, 60], [0.45, 52], [0.6, 46], [0.75, 42], [0.9, 30], [1, 26]],
    post: [[0, 26], [0.25, 30], [0.5, 32], [0.75, 34], [1, 36]],
    outcomePct: +38,
    blurb: 'Meta at $88 in November 2022, down 77% from its high. The layoffs landed, the "year of efficiency" followed, and the stock roughly 7x\'d over the next two years — one of the great comebacks in market history. Maximum pessimism rarely announces itself politely.',
  },
  {
    id: 'zm-2020',
    ticker: 'ZM',
    name: 'Zoom',
    revealDate: 'October 2020',
    story: 'The whole world lives on this app now',
    headlines: [
      'Daily meeting participants are up 30x year over year.',
      'The company is now worth more than ExxonMobil.',
      'Analysts debate whether offices will ever fully reopen.',
    ],
    pre: [[0, 12], [0.15, 18], [0.3, 28], [0.45, 42], [0.6, 55], [0.75, 68], [0.88, 92], [1, 100]],
    post: [[0, 100], [0.2, 88], [0.4, 72], [0.7, 76], [1, 70]],
    outcomePct: -30,
    blurb: 'Zoom at its October 2020 peak — $568 a share, bigger than Exxon. Two weeks later the vaccine trial results dropped and the entire stay-at-home trade unwound. It never saw that price again. "This changes everything forever" is usually priced in by the time you hear it.',
  },
  {
    id: 'amzn-1999',
    ticker: 'AMZN',
    name: 'Amazon',
    revealDate: 'December 1999',
    story: 'It loses money on every order',
    headlines: [
      'Up thousands of percent since its IPO three years ago.',
      'The company has never turned an annual profit.',
      'Its founder was just named Person of the Year.',
    ],
    pre: [[0, 12], [0.18, 22], [0.35, 30], [0.5, 45], [0.62, 60], [0.75, 55], [0.88, 78], [1, 100]],
    post: [[0, 100], [0.25, 84], [0.5, 76], [0.75, 66], [1, 62]],
    outcomePct: -38,
    blurb: 'Amazon at the December 1999 dot-com peak. It fell ~38% in two months and ~93% by 2001 — then became one of the best investments ever made. Both things are true: the bubble was real, and so was the business. Surviving the drawdown was the hard part.',
  },
  {
    id: 'csco-2000',
    ticker: 'CSCO',
    name: 'Cisco',
    revealDate: 'March 2000',
    story: 'The most valuable company on earth',
    headlines: [
      'It just passed Microsoft as the world\'s biggest company by market cap.',
      'It sells the plumbing of the internet — and the internet is the future.',
      'The stock trades at nearly 200 times earnings. Analysts see more upside.',
    ],
    pre: [[0, 20], [0.2, 28], [0.4, 36], [0.6, 48], [0.8, 70], [1, 100]],
    post: [[0, 100], [0.4, 78], [0.7, 84], [1, 86]],
    outcomePct: -14,
    blurb: 'Cisco, March 27, 2000 — the exact day it became the most valuable company on earth, and the exact top of the dot-com bubble. The business kept growing for decades; the stock didn\'t see that price again for over 20 years. Being right about the future doesn\'t save you from the price you paid.',
  },
  {
    id: 'nflx-2011',
    ticker: 'NFLX',
    name: 'Netflix',
    revealDate: 'July 2011',
    story: 'A 60% price hike, announced by blog post',
    headlines: [
      'The company just split its DVD and streaming plans — a ~60% price increase.',
      'Subscribers are furious; the cancellation hashtag is trending.',
      'The stock has been a 5x in two years and sits near all-time highs.',
    ],
    pre: [[0, 20], [0.25, 30], [0.5, 45], [0.75, 70], [1, 100]],
    post: [[0, 100], [0.4, 90], [0.7, 86], [1, 84]],
    outcomePct: -16,
    blurb: 'Netflix, July 2011 — days before the Qwikster fiasco. It lost 800,000 subscribers, the stock fell ~75% by year end, and the CEO publicly apologized. Then it 100x\'d over the next decade. Great companies make unforced errors too; the question is what you do at −75%.',
  },
  {
    id: 'tsla-2019',
    ticker: 'TSLA',
    name: 'Tesla',
    revealDate: 'June 2019',
    story: 'Weeks from the edge, says the CEO',
    headlines: [
      'An internal email says the company is ~10 months from running out of money.',
      'Deliveries missed badly; the stock is at a 2.5-year low.',
      'Wall Street debates bankruptcy scenarios; short sellers are all over it.',
    ],
    pre: [[0, 100], [0.2, 92], [0.4, 96], [0.6, 78], [0.8, 62], [1, 52]],
    post: [[0, 52], [0.4, 60], [0.7, 65], [1, 68]],
    outcomePct: +31,
    blurb: 'Tesla, June 3, 2019 — the modern low. It rallied 31% in a month, and within 18 months it was up ~20x and joining the S&P 500. The most shorted stock in America became the decade\'s biggest squeeze. Peak fear and peak opportunity keep the same calendar.',
  },
  {
    id: 'spy-2020',
    ticker: 'SPY',
    name: 'S&P 500',
    revealDate: 'March 2020',
    story: 'The world is closed until further notice',
    headlines: [
      'Global lockdowns expand; the fastest 30% drop in stock market history.',
      'Unemployment claims are printing numbers with no historical precedent.',
      'The Fed just announced unlimited bond buying to backstop markets.',
    ],
    pre: [[0, 78], [0.3, 84], [0.55, 92], [0.7, 100], [0.82, 78], [0.92, 66], [1, 62]],
    post: [[0, 62], [0.3, 70], [0.6, 74], [1, 78]],
    outcomePct: +25,
    blurb: 'The S&P 500 on March 23, 2020 — the COVID bottom, the same day the Fed went unlimited. Stocks jumped 25% in a month while the news got worse every single day. The market doesn\'t trade the headlines; it trades the change in the headlines.',
  },
];
